[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llmtest"
version = "0.1.0"
description = "Release-notes-driven LLM testing tool (MySQL)"
requires-python = ">=3.9"
dependencies = []

